# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Irecord',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pname', models.CharField(max_length=20)),
                ('vendor', models.CharField(max_length=50)),
                ('mrp', models.IntegerField(default=0)),
                ('batch_num', models.IntegerField()),
                ('batch_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventm.Role')),
            ],
        ),
    ]
