# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventm', '0002_auto_20181026_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irecord',
            name='status',
        ),
        migrations.AddField(
            model_name='irecord',
            name='appr_status',
            field=models.BooleanField(default=False),
        ),
    ]
